In [1]:
import torch

In [2]:
import numpy as np

1D array with 3 elements

In [3]:
x = torch.empty(3)
print(x)

tensor([2.8231e+23, 6.8608e+22, 1.9862e+29])


2D array with 3 elements in each 1D array

In [4]:
x = torch.empty(2, 3) # x = torch.empty((2, 3))
print(x)

tensor([[-2.0857e+37,  4.5311e-41,  2.8956e+23],
        [ 3.1061e-41,  4.4842e-44,  0.0000e+00]])


2D array filled with ones

In [5]:
x = torch.ones(5, 3) # x = torch.empty((5, 3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


2D array filled with zeros

In [6]:
x = torch.zeros(5, 3) # x = torch.zeros((5, 3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Datatypes

In [7]:
x = torch.ones(4, 5) # x = torch.ones((4, 5))
print(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [8]:
x.dtype

torch.float32

In [9]:
x = torch.ones(4, 5, dtype=torch.int64)
print(x)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])


In [10]:
x.dtype

torch.int64

`.size()` and `.shape`

In [11]:
x = torch.zeros(3, 4)

In [12]:
print(f'x.size() = {x.size()}\nx.size(0) = {x.size(0)}\nx.size(1) = {x.size(1)}')

x.size() = torch.Size([3, 4])
x.size(0) = 3
x.size(1) = 4


In [13]:
print(f'x.shape = {x.shape}\nx.shape[0] = {x.shape[0]}\nx.shape[1] = {x.shape[1]}')

x.shape = torch.Size([3, 4])
x.shape[0] = 3
x.shape[1] = 4


Elementwise operations

In [14]:
# 2x2 tensors with random initialized integer values in between 1 and 10
x = torch.randint(1,10,(2,2))
y = torch.randint(1,10,(2,2))
print(x)
print(y)

# pairwise addition
print(x+y) # print(torch.add(x,y))

# pairwise subtraction
print(x-y) # print(torch.sub(x,y))

# pairwise multiplication
print(x*y) # print(torch.mul(x,y))

# pairwise division
print(x/y) # print(torch.div(x,y))

tensor([[5, 9],
        [8, 6]])
tensor([[6, 2],
        [9, 7]])
tensor([[11, 11],
        [17, 13]])
tensor([[-1,  7],
        [-1, -1]])
tensor([[30, 18],
        [72, 42]])
tensor([[0.8333, 4.5000],
        [0.8889, 0.8571]])


Add x, y and put the result on y

In [15]:
# in-place operation is common for all all operations

# example for in-place addition
y.add_(x)
print(y)

tensor([[11, 11],
        [17, 13]])


Tensor with some elemnts

In [16]:
x = torch.tensor([1,3,5,7], dtype=torch.int64)
print(x.shape)

torch.Size([4])


Tensor with 4x1 matrix

In [17]:
x = torch.tensor([[1],[3],[5],[7]], dtype=torch.int64)
print(x.shape)

torch.Size([4, 1])


Tensor with 1x4 matrix

In [18]:
y = torch.tensor([[2,4,6,8]], dtype=torch.int64)
print(y.shape)

torch.Size([1, 4])


Tensor with 4x4 matrix z = x*y

In [19]:
z = x@y
print(z)

tensor([[ 2,  4,  6,  8],
        [ 6, 12, 18, 24],
        [10, 20, 30, 40],
        [14, 28, 42, 56]])


Tensor with random initializae values between 0 - 1

In [20]:
x = torch.rand(2, 3)
y = torch.rand(3, 2)
print(x)
print(y)

tensor([[0.8870, 0.2759, 0.0816],
        [0.1387, 0.2024, 0.5981]])
tensor([[0.3858, 0.5155],
        [0.2347, 0.9938],
        [0.7528, 0.7864]])


Matrix Multiplication with @

In [21]:
print(x@y)

tensor([[0.4685, 0.7956],
        [0.5513, 0.7430]])


Slicing

In [22]:
x = torch.randint(1,10,(5,4))
print(x)

tensor([[4, 8, 3, 1],
        [7, 8, 6, 4],
        [6, 7, 6, 7],
        [7, 6, 9, 7],
        [9, 2, 7, 7]])


In [23]:
print(x[1,1])

tensor(8)


In [24]:
print(x[1,1].item())

8


In [25]:
print(x[1, :])

tensor([7, 8, 6, 4])


In [26]:
print(x[:, 1])

tensor([8, 8, 7, 6, 2])


In [27]:
print(x[:, 1].shape)

torch.Size([5])


Reshape

In [28]:
print(x[:, 1].view(5,1))

tensor([[8],
        [8],
        [7],
        [6],
        [2]])


Tensor -> Numpy

In [29]:
a = torch.ones(2, 3)
print(a)

b = a.numpy()
print(b)

b[0,0] = 0
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[0., 1., 1.],
        [1., 1., 1.]])


Numpy -> Tensor

In [34]:
a = np.ones((2, 3))
print(a)

b = torch.from_numpy(a)
print(b)

b[0,0] = 0
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
[[0. 1. 1.]
 [1. 1. 1.]]


Using CUDA

In [39]:
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

x = torch.ones(5, device=device)
print(x.device)

cuda:0


Numpy doesn't support CUDA. So, convert back to CPU

In [40]:
x = x.to('cpu')
print(x.device)

cpu


In [41]:
x = x.numpy()
print(type(x))

<class 'numpy.ndarray'>
